<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-08T13:11:03 IST" name="Default suite" finished-at="2023-02-08T13:11:32 IST" duration-ms="29558">
    <groups>
      <group name="Regression">
        <method signature="LoginTest.verifybuildname()[pri:-1, instance:test.LoginTest@4d465b11]" name="verifybuildname" class="test.LoginTest"/>
      </group> <!-- Regression -->
      <group name="smoke">
        <method signature="LoginTest.verifybuildname()[pri:-1, instance:test.LoginTest@4d465b11]" name="verifybuildname" class="test.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-02-08T13:11:03 IST" name="Default test" finished-at="2023-02-08T13:11:32 IST" duration-ms="29558">
      <class name="test.LoginTest">
        <test-method is-config="true" signature="initBrowser()[pri:0, instance:test.LoginTest@4d465b11]" started-at="2023-02-08T13:11:03 IST" name="initBrowser" finished-at="2023-02-08T13:11:30 IST" duration-ms="27190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initBrowser -->
        <test-method is-config="true" signature="pageObjects()[pri:0, instance:test.LoginTest@4d465b11]" started-at="2023-02-08T13:11:30 IST" name="pageObjects" finished-at="2023-02-08T13:11:30 IST" duration-ms="70" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageObjects -->
        <test-method signature="verifybuildname()[pri:-1, instance:test.LoginTest@4d465b11]" started-at="2023-02-08T13:11:30 IST" name="verifybuildname" finished-at="2023-02-08T13:11:31 IST" duration-ms="1021" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [OrangeHRM] but found [Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [OrangeHRM] but found [Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.LoginTest.verifybuildname(LoginTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifybuildname -->
        <test-method is-config="true" signature="tearDownEnvironment()[pri:0, instance:test.LoginTest@4d465b11]" started-at="2023-02-08T13:11:31 IST" name="tearDownEnvironment" finished-at="2023-02-08T13:11:32 IST" duration-ms="1194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownEnvironment -->
      </class> <!-- test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
